add buildpack badges
heroku/buildpacks-nodejs pull request #45
Opened 2021-04-27 20:16 UTC by lillianzhang331

2021-04-29 14:04 UTC, schneems approved these changes

2021-04-29 15:29 UTC, danielleadams requested changes
Looks great! A few things:
- the name under Engine should be "Node.js Runtime"
- Typescript should be "TypeScript"

2021-05-03 14:30 UTC, danielleadams commented
@lillianzhang331 The Engine should have been changed to Node.js Runtime, you changed "Node.js" instead (with id heroku/nodejs).

2021-05-03 18:17 UTC, danielleadams approved these changes
Thanks!

2021-05-03 18:17 UTC, merged